# Generated by Django 5.1.2 on 2024-10-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(default='https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', null=True, upload_to='images/'),
        ),
    ]
