# Generated by Django 5.1.2 on 2024-10-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_img_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_publish', 'Can publish articles')]},
        ),
    ]
